const projects=[
{id:1,name:'Nâng cấp, xây dựng hệ thống thủy lợi phục vụ tưới cho cây trồng cạn (WEIDAP/ADB8)',area:'Ea Drăng · Ea Kar · Krông Pắc · Ea Kly · Ea Phê · Quảng Phú',progress:67,status:'risk',delivered:'Hoàn thành tại Ea Drăng và Ea Kar; Krông Pắc còn 3,74 ha',remaining:'3,74 ha tại Krông Pắc; các địa bàn khác chưa triển khai',deadline:'03/8/2026',issues:[{title:'Chậm xác nhận nguồn gốc đất',text:'Đợt 1 mới xác nhận 17/52 hộ; đợt 2 chưa xác nhận 54 hộ. Một số trường hợp thường trú ngoài địa bàn chưa có phản hồi.',task:'Tập trung nhân lực hoàn thành xác nhận nguồn gốc sử dụng đất đợt 1 và 2.',unit:'UBND xã Krông Pắc',due:'22/7/2026'},{title:'Kiểm đếm sau điều chỉnh ranh GPMB',text:'Cần kiểm đếm lại 159 thửa/134 hộ/2,2504 ha; địa hình và hàng rào gây khó khăn di chuyển.',task:'Hoàn thành kiểm đếm và bàn giao hồ sơ xác nhận nguồn gốc đất.',unit:'Ban A · UBND xã Krông Pắc',due:'31/7–03/8/2026'},{title:'06 hộ chưa phối hợp kiểm đếm',text:'Các hộ đề nghị điều chỉnh tuyến kênh; tư vấn xác định không thể điều chỉnh vì ảnh hưởng áp lực nước.',task:'Tuyên truyền, vận động 06 hộ phối hợp kiểm đếm.',unit:'UBND xã Krông Pắc',due:'22/7/2026'}]},
{id:2,name:'Nâng cấp, mở rộng đường 19 tháng 5 (giai đoạn 1)',area:'Phường Ea Kao',progress:50.05,status:'risk',delivered:'16.429,5 m² · 64 hộ',remaining:'16.395,6 m² · 190 hộ',deadline:'25/7/2026',issues:[{title:'08 hộ chưa bàn giao mặt bằng',text:'08 hộ/11 thửa/2.507,1 m² đề nghị hỗ trợ tài sản xây dựng trên đất nông nghiệp.',task:'Tiếp tục vận động; hoàn thiện hồ sơ cưỡng chế.',unit:'UBND phường Ea Kao',due:'22/7/2026'},{title:'92 hộ chưa đủ điều kiện lập phương án',text:'Vướng nguồn gốc đất, đo đạc sai vị trí/diện tích, ảnh hưởng kết cấu nhà, chưa tìm được chủ và tái định cư.',task:'Hoàn thiện xác minh, đo đạc và phương án bồi thường theo từng nhóm.',unit:'Ban BMT · VPĐKĐĐ · UBND phường',due:'25/7/2026'},{title:'57 hộ đã công khai phương án',text:'62 thửa/2.769,5 m² đã công khai dự thảo phương án 116/PA-DABMT.',task:'Tổng hợp ý kiến, hoàn thiện thẩm định và phê duyệt.',unit:'Ban BMT',due:'Sau 20/7/2026'}]},
{id:3,name:'Đường Tôn Đức Thắng, thành phố Buôn Ma Thuột',area:'Phường Buôn Ma Thuột · Phường Tân An',progress:34.8,status:'risk',delivered:'Buôn Ma Thuột: 1.948,8 m²; Tân An: 4.212,4 m²',remaining:'Buôn Ma Thuột: 6.578,7 m²; Tân An: 9.673 m²',deadline:'20/8/2026',issues:[{title:'Chính sách bồi thường và tái định cư',text:'Các nhóm hộ đề nghị bồi thường về đất, phản ánh giá thấp và đề nghị giao đất tái định cư.',task:'Vận động; xem xét điều kiện giao đất và hoàn thiện quy trình thu hồi/cưỡng chế.',unit:'UBND phường Buôn Ma Thuột',due:'20/8/2026'},{title:'Xác minh năm xây dựng tại Tân An',text:'38 hộ khu tập thể Công ty cao su chưa thống nhất năm xây dựng sau đối thoại lần 2.',task:'Xác minh lại năm xây dựng, hoàn thiện phương án.',unit:'UBND phường Tân An · Ban BMT',due:'22/7/2026'},{title:'Vướng chi trả và bàn giao',text:'Còn các hộ đã phê duyệt nhưng chưa nhận tiền; 18 hộ vướng nguồn vốn chi trả.',task:'Bố trí vốn, chi trả và vận động bàn giao.',unit:'Sở Tài chính · Sở NN&MT · Ban BMT',due:'28/7/2026'}]},
{id:4,name:'Cải tạo, nâng cấp Tỉnh lộ 1 từ cầu Buôn Ky đến Km49+00',area:'Thành Nhất · Ea Nuôl · Buôn Đôn · Ea Wer',progress:99.52,status:'risk',delivered:'Hoàn thành tại Thành Nhất, Ea Nuôl, Buôn Đôn; Ea Wer đạt 95,37%',remaining:'Ea Wer còn 249,8 m² / 02 hộ',deadline:'28/7/2026',issues:[{title:'Hộ ông Đoàn Thanh Hùng chưa nhận tiền',text:'Đã phê duyệt phương án hỗ trợ bổ sung; đang chờ chi trả và vận động bàn giao.',task:'Mời chi trả, vận động; hoàn thiện hồ sơ cưỡng chế nếu không đồng thuận.',unit:'Ban QLDA ĐTXD Buôn Hồ · UBND xã Ea Wer · Ban A',due:'22–28/7/2026'},{title:'Hộ ông Đoàn Văn Dương',text:'Đã xác định ranh giới và có trích lục; đang chờ lập, công khai phương án.',task:'Hoàn thiện dự thảo, xác nhận nguồn gốc đất và thẩm định.',unit:'Ban QLDA ĐTXD Buôn Hồ · UBND xã Ea Wer',due:'21–26/7/2026'}]},
{id:5,name:'Cải tạo, nâng cấp Tỉnh lộ 13, đoạn Km6+840 – Km25+00',area:'Xã Cư Prao · Xã M’Drắk',progress:92.45,status:'risk',delivered:'Cư Prao: 10.638 m²; M’Drắk đã hoàn thành 2.358,9 m²',remaining:'Cư Prao còn 1.882,4 m² / 09 hộ',deadline:'21/8/2026',issues:[{title:'Thiếu hồ sơ thu hồi đất lòng hồ',text:'09 hộ có khả năng đã được thu hồi đất bởi dự án thủy điện Krông H’Năng nhưng xã chưa tìm được hồ sơ.',task:'Cung cấp ranh GPMB lòng hồ; hoàn thành kiểm đếm, xác nhận nguồn gốc và phương án.',unit:'Sở NN&MT · UBND xã Cư Prao',due:'21/7–21/8/2026'}]},
{id:6,name:'Đường giao thông từ Quốc lộ 26 đi xã Ea Ô kết nối trung tâm xã Vụ Bổn',area:'Xã Ea Ô · Xã Ea Kar',progress:12.2,status:'risk',delivered:'Ea Ô: 0,1/0,5; Ea Kar: 0,5/4,5',remaining:'Còn đo đạc, kiểm đếm và phê duyệt nhiều phương án',deadline:'15/8/2026',issues:[{title:'Sai khác trích lục và hiện trạng',text:'Một số thửa có GCN hợp pháp nhưng trích lục chưa đúng hiện trạng; đang đo đạc chỉnh lý.',task:'Đôn đốc đo đạc, hoàn thiện kiểm đếm và toàn bộ phương án.',unit:'Ban Ea Kar · Đơn vị đo đạc',due:'25/7–15/8/2026'},{title:'04 trụ điện chưa di dời',text:'Còn 04/28 trụ điện nằm trên mặt bằng thi công.',task:'Di dời khỏi phạm vi đường để bàn giao cho nhà thầu.',unit:'Đơn vị thi công đường điện',due:'31/7/2026'},{title:'Hộ dân chưa thống nhất phương án',text:'Một số hộ không đồng ý với phương án bồi thường GPMB.',task:'Tiếp tục đối thoại, hoàn thiện thẩm định và phê duyệt các phương án theo đợt.',unit:'UBND xã Ea Kar · Ban Ea Kar',due:'15/8/2026'}]},
{id:7,name:'Nhà máy điện gió NT1, NT2 (75 MW)',area:'Cuôr Đăng · Cư Bao · Ea Knuếc · Krông Pắc',progress:null,status:'planned',delivered:'Chưa phát sinh số liệu GPMB',remaining:'Đang khảo sát vị trí tuabin, trạm biến áp và đường dây',deadline:'Khoảng 3 tháng',issues:[{title:'Đang hoàn thiện cơ sở triển khai đất đai',text:'Dự án được chấp thuận chủ trương đầu tư ngày 25/6/2026; nhà đầu tư đang thuê tư vấn khảo sát và lập báo cáo nghiên cứu khả thi.',task:'Hoàn thành khảo sát, FS và phương án đền bù trước khi thực hiện thủ tục đất đai.',unit:'Nhà đầu tư',due:'Theo tiến độ 20–45 ngày'}]},
{id:8,name:'Nhà máy điện gió Krông Năng 1.1, 1.2 (80 MW)',area:'Xã Tam Giang',progress:null,status:'planned',delivered:'Chưa phát sinh số liệu GPMB',remaining:'Đang khảo sát vị trí tuabin, trạm biến áp và đường dây',deadline:'Khoảng 3 tháng',issues:[{title:'Đang hoàn thiện cơ sở triển khai đất đai',text:'Dự án được chấp thuận chủ trương đầu tư ngày 25/6/2026; nhà đầu tư đang thuê tư vấn khảo sát và lập báo cáo nghiên cứu khả thi.',task:'Hoàn thành khảo sát, FS và phương án đền bù trước khi thực hiện thủ tục đất đai.',unit:'Nhà đầu tư',due:'Theo tiến độ 20–45 ngày'}]}
];
// Chuẩn hóa diện tích theo các cột Tổng DT thu hồi và Đã bàn giao trong tệp nguồn.
const areaMetrics={
  1:{progress:38.28,areaRatio:'2,32/6,06 ha (03 địa bàn có số liệu)',delivered:'2,32/6,06 ha tại Ea Drăng, Ea Kar và Krông Pắc'},
  2:{progress:50.05,areaRatio:'16.429,5/32.825,1 m²'},
  3:{progress:27.49,areaRatio:'6.161,2/22.412,9 m²',delivered:'6.161,2/22.412,9 m² (Buôn Ma Thuột và Tân An)'},
  4:{progress:98.31,areaRatio:'1,45467/1,47965 ha',delivered:'1,45467/1,47965 ha tại các địa bàn có diện tích thu hồi'},
  5:{progress:87.35,areaRatio:'12.996,9/14.879,3 m²',delivered:'12.996,9/14.879,3 m² tại Cư Prao và M’Drắk'},
  6:{progress:12,areaRatio:'0,6/5,0 ha',delivered:'0,6/5,0 ha tại Ea Ô và Ea Kar'},
  7:{progress:null,areaRatio:'Chưa có số liệu diện tích'},
  8:{progress:null,areaRatio:'Chưa có số liệu diện tích'}
};
projects.forEach(p=>Object.assign(p,areaMetrics[p.id]));
const labels={done:'Đã hoàn thành',risk:'Cần đôn đốc',planned:'Đang chuẩn bị'};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>n==null?'Chưa xác định':n.toLocaleString('vi-VN',{maximumFractionDigits:2})+'%';
const avg=projects.filter(p=>p.progress!=null).reduce((a,p)=>a+p.progress,0)/projects.filter(p=>p.progress!=null).length;
document.querySelector('#kpis').innerHTML=[['Dự án đang theo dõi',projects.length,'Theo phụ lục Tổ công tác 04'],['Có tỷ lệ GPMB',projects.filter(p=>p.progress!=null).length+'/'+projects.length,'02 dự án đang chuẩn bị'],['Tiến độ bình quân',fmt(avg),'06 dự án có tỷ lệ'],['Đạt từ 90% trở lên',projects.filter(p=>p.progress>=90).length,'Theo tỷ lệ trong nguồn']].map(x=>`<article class="kpi"><span class="label">${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join('');
document.querySelector('#chart').innerHTML=[...projects].sort((a,b)=>(b.progress??-1)-(a.progress??-1)).map(p=>`<div class="bar-row"><div class="bar-name">${p.id}. ${esc(p.name)}</div><div class="track"><div class="fill ${p.progress!=null&&p.progress<60?'low':''}" style="width:${p.progress||0}%"></div></div><div class="bar-value"><strong>${fmt(p.progress)}</strong><small>${esc(p.areaRatio)}</small></div></div>`).join('');
const area=document.querySelector('#area');[...new Set(projects.flatMap(p=>p.area.split(' · ')))].sort((a,b)=>a.localeCompare(b,'vi')).forEach(a=>area.add(new Option(a,a)));
function card(p){const pc=p.progress==null?0:p.progress;return `<details class="project"><summary><span class="number">${p.id}</span><div><h3>${esc(p.name)}</h3><div class="meta"><span class="pill">${esc(p.area)}</span><span class="pill ${p.status}">${labels[p.status]}</span><span class="pill">Mốc: ${esc(p.deadline)}</span></div></div><div class="progress"><strong>${fmt(p.progress)}</strong><small>Tiến độ GPMB</small></div><span class="detail-toggle"><span>Xem chi tiết</span><b aria-hidden="true">+</b></span></summary><div class="project-body"><div class="meter"><span>0%</span><div class="track"><div class="fill ${pc<60?'low':''}" style="width:${pc}%"></div></div><b>${fmt(p.progress)}</b></div><div class="facts"><div class="fact"><span>Đã bàn giao</span><strong>${esc(p.delivered)}</strong></div><div class="fact"><span>Còn lại / bước tiếp</span><strong>${esc(p.remaining)}</strong></div><div class="fact"><span>Mốc chính</span><strong>${esc(p.deadline)}</strong></div></div><div class="issues">${p.issues.map(i=>`<article class="issue"><div class="issue-head"><h4>${esc(i.title)}</h4><span class="deadline">${esc(i.due)}</span></div><p>${esc(i.text)}</p><dl><dt>Nhiệm vụ</dt><dd>${esc(i.task)}</dd><dt>Đơn vị</dt><dd>${esc(i.unit)}</dd><dt>Trạng thái</dt><dd>${labels[p.status]}</dd></dl></article>`).join('')}</div></div></details>`}
function render(){const q=document.querySelector('#search').value.trim().toLocaleLowerCase('vi');const a=area.value;const s=document.querySelector('#status').value;const list=projects.filter(p=>(!q||[p.name,p.area,...p.issues.flatMap(i=>[i.title,i.text,i.task,i.unit])].join(' ').toLocaleLowerCase('vi').includes(q))&&(!a||p.area.split(' · ').includes(a))&&(!s||p.status===s));document.querySelector('#projects').innerHTML=list.map(card).join('');document.querySelector('#result-count').textContent=`Hiển thị ${list.length}/${projects.length} dự án`;document.querySelector('#empty').hidden=!!list.length}
['search','area','status'].forEach(id=>document.querySelector('#'+id).addEventListener(id==='search'?'input':'change',render));document.querySelector('#reset').addEventListener('click',()=>{document.querySelector('#search').value='';area.value='';document.querySelector('#status').value='';render()});render();
const cardWithoutAreaRatio=card;
card=p=>cardWithoutAreaRatio(p).replace('<small>Tiến độ GPMB</small>',`<small>Đã GPMB: ${esc(p.areaRatio)}</small>`);
render();
